# Generated by Django 4.1.5 on 2023-02-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('TareaId', models.AutoField(primary_key=True, serialize=False)),
                ('TareaNombre', models.CharField(max_length=100)),
                ('CreacionTarea', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('1', 'Por hacer'), ('2', 'En proceso'), ('3', 'Realizada'), ('4', 'No Realizada')], default='1', max_length=50)),
            ],
        ),
    ]
