# Generated by Django 4.1.5 on 2023-02-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_alter_tareas_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='Status',
            field=models.CharField(choices=[('Por hacer', 'Por hacer'), ('En proceso', 'En proceso'), ('Realizada', 'Realizada'), ('No Realizada', 'No Realizada')], default='Por hacer', max_length=50),
        ),
    ]
