# Generated by Django 4.1.5 on 2023-02-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_alter_tareas_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='ActualizacionTarea',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
