# Generated by Django 4.1.1 on 2023-02-24 04:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_tareas_actualizaciontarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='ActualizacionTarea',
            field=models.DateTimeField(auto_now=True, help_text='Formato: AAAA-MM-DD HH:MM:SS', verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='CreacionTarea',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Formato: AAAA-MM-DD HH:MM', verbose_name='Fecha de creación'),
        ),
    ]
